schemaVersion: 2.2.0
metadata:
  generateName: ${{values.artifact_id}} 
components:
  - name: development-tooling
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      env:
        - name: PYTHONPATH
          value: "${PROJECT_SOURCE}"
        - name: PYTHON_HTTP_HOST 
          value: "0.0.0.0"
        - name: VIRTUAL_ENV
          value: "/home/user/.venv"
        - name: PATH
          value: "/home/user/.venv/bin:${PATH}"
      memoryLimit: 5Gi
      cpuLimit: 2500m
      endpoints:
        - name: pred-model-dev
          targetPort: 8080
          exposure: public
          secure: false
          protocol: http
          path: /
        - name: debug
          targetPort: 5678
          exposure: none
          secure: false
          protocol: tcp
commands:
  - id: install-dependencies
    exec:
      label: "1. Install Python dependencies"
      component: development-tooling
      commandLine: "python -m venv .venv && . .venv/bin/activate && if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo 'No requirements.txt found. Please create one first.'; fi"
      group:
        kind: build
        isDefault: true
  - id: start-dev
    exec:
      label: "2. Start Development server"
      component: development-tooling
      commandLine: "if [ -f app.py ]; then python app.py; else echo 'No app.py found. Please create your application entry point first.'; fi"
      group:
        kind: run
        isDefault: true
  - id: debug
    exec:
      label: "3. Start Development server with debugger"
      component: development-tooling
      commandLine: "if [ -f app.py ]; then python -m debugpy --listen 0.0.0.0:5678 app.py; else echo 'No app.py found. Please create your application entry point first.'; fi"
      group:
        kind: debug
        isDefault: true